Populate table view welcome scene
Madalin584/20200307JavaFXProductsFromMarketPlace pull request #14
Opened 2020-03-13 22:07 UTC by Madalin584

Implemented WelcomeController

2020-03-14 09:42 UTC, stefan2212 requested changes

2020-03-14 09:42 UTC, stefan2212 commented on src/main/java/sample/controller/WelcomeController.java
> +        log.info("At the end of the method");
Why do you need to load at the end of the method? :D

2020-03-14 09:42 UTC, stefan2212 commented on src/main/java/sample/dao/ProductDAO.java
> +    List<Product> get();
getAll made a lot of more sense than get

2020-03-14 09:42 UTC, stefan2212 commented on src/main/java/sample/controller/LoginController.java
> +            throw new UserException("User object is null");
Why do you want to throw an exception?

2020-03-14 09:42 UTC, stefan2212 commented on src/main/java/sample/dao/ProductDAOImpl.java
> +    public void add() {
I think this method should have a parameter

2020-03-14 09:42 UTC, stefan2212 commented on src/main/java/sample/dao/ProductDAOImpl.java
> +    public void remove() {
also this

2020-03-14 09:42 UTC, stefan2212 commented on src/main/java/sample/dao/ProductDAOImpl.java
> +    public void buy() {
and this

2020-03-14 09:42 UTC, stefan2212 commented on src/main/java/sample/dao/ProductDAO.java
> +    List<Product> get();
or getAllProducts

2020-03-14 11:37 UTC, PinteleiDamian approved these changes

2020-03-14 16:01 UTC, PinteleiDamian approved these changes

2020-03-14 16:30 UTC, stefan2212 requested changes

2020-03-14 16:30 UTC, stefan2212 commented on src/main/java/sample/dao/ProductDAO.java
> +    //delete by ID or by Name ???
In your case you can delete by id. 
Because you are using the entire Product object.

2020-03-15 06:52 UTC, Madalin584 commented on src/main/java/sample/controller/LoginController.java
> +            throw new UserException("User object is null");
Because user is null, but i think that we don't need to break program execution when user variable is null

2020-03-15 06:52 UTC, Madalin584 commented on src/main/java/sample/controller/WelcomeController.java
> +        log.info("At the end of the method");
I've seen this in tutorial

2020-03-15 06:52 UTC, Madalin584 commented on src/main/java/sample/dao/ProductDAOImpl.java
> +    public void remove() {
We will delete byId or byName of the product ?

2020-03-15 06:52 UTC, Madalin584 commented on src/main/java/sample/dao/ProductDAOImpl.java
> +    public void buy() {
buy(Product product)

2020-03-15 20:55 UTC, stefan2212 approved these changes

2020-03-15 21:06 UTC, merged